### ISSUE TITLE
Support for Cake 0.26+

### ISSUE THREAD

**Issue by thnk2wn** [cake-contrib/Cake.Karma#10]
Currently I'm using the latest Cake 0.27.0 and when using Cake.Karma I get

<pre>
Error: The assembly 'Cake.Karma, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.23.0).
This assembly must reference at least Cake.Core version 0.26.0.
</pre>

It'd be great if this supported the latest to avoid downgrades of Cakes or other hacks.

**Comment by gep13** [comment]
@thnk2wn thanks for raising this, I appreciate it.  This will be covered in issue #11, and as such, I am going to go ahead and close this issue to avoid duplication.
